name: CI / Entrena + Valida

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *' 

jobs:
  train-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install torch torchvision
          pip install -r requirements.txt

      - name: Entrenar modelo
        run: |
          source venv/bin/activate
          python model/train.py

      - name: Validar modelo
        run: |
          source venv/bin/activate
          python validate/validate.py